name: devopsdb

services:
  bytebase:
    image: bytebase/bytebase:2.19.0
    container_name: bytebase
    ports:
      - 8080:8080
    volumes:
      - ~/.bytebase/data:/var/opt/bytebase
    networks:
      - appnet
  database:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    env_file:
      - path: ./mysql.env
        required: true
    networks:
      - appnet

# Docker Networks
networks:
  appnet:
    driver: bridge